package unach.sindicato.api.utils.exceptions;

public enum Errors {
    INVALID_TOKEN_ERROR,
    WITHOUT_AUTHORIZATION_ERROR,
    QUERY_WITHOUT_RESPONSE_ERROR,
    ILLEGAL_PARAMETER_ERROR,
    ROLLBACK_ACTION_ERROR,
    UNINTELIGIBLE_REQUEST_ERROR,
    SERVER_ERROR,
}
